# Generated by Django 3.2.8 on 2021-10-11 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TransportApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TransportApp',
            new_name='Transport',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='klient',
            new_name='client',
        ),
    ]
