# Generated by Django 3.2.8 on 2021-10-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransportApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='geo',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
