# Generated by Django 3.2.8 on 2021-10-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransportApp', '0002_auto_20211018_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.IntegerField(choices=[(1, 'Nowe'), (2, 'Zdefiniowano Transport'), (3, 'Zrealizowane'), (4, 'Anulowane')], default=1),
        ),
    ]
