# Generated by Django 3.2.8 on 2021-10-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransportApp', '0002_orders_geo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='geo',
            new_name='lat',
        ),
        migrations.AddField(
            model_name='orders',
            name='lon',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
