# Generated by Django 3.2.8 on 2021-10-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransportApp', '0002_auto_20211011_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
