# Generated by Django 3.2.8 on 2021-10-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransportApp', '0003_alter_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='opis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
