# Generated by Django 3.2.8 on 2021-10-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransportApp', '0005_alter_orders_delivery_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='distance',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='time',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
