# Generated by Django 3.2.8 on 2021-10-25 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TransportApp', '0006_auto_20211025_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transport',
            name='order',
        ),
        migrations.AddField(
            model_name='transport',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TransportApp.orders'),
            preserve_default=False,
        ),
    ]
